version: '3'
services:
    backend:
        build: .
        image: tentaculaire
        ports:
            - "8080:8080"
        networks:
            tentanet:
                ipv4_address: 172.20.1.2
        env_file:
            - .env
        depends_on:
            - mongo
        restart: always
    mongo:
        image: mongo:4.0.4
        volumes:
            - ~/mongo/data/data/db:/data/db
        ports:
            - "27017-27019:27017-27019"
        networks:
            tentanet:
                ipv4_address: 172.20.1.3



networks:
    tentanet:
        ipam:
            driver: default
            config:
                - subnet: 172.20.1.0/16
            

